# Generated by Django 4.1 on 2023-12-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
