# Generated by Django 4.1 on 2023-12-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userinfo_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, height_field=48, upload_to='images/%Y%m%d', width_field=48),
        ),
    ]
